/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mymobkit_video_JpegHandler */

#ifndef _Included_com_mymobkit_video_JpegHandler
#define _Included_com_mymobkit_video_JpegHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shmccam_webcam_video_JpegHandler
 * Method:    initRgb
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mymobkit_video_JpegHandler_initRgb
  (JNIEnv *, jobject);

/*
 * Class:     com_shmccam_webcam_video_JpegHandler
 * Method:    initYuv
 * Signature: (III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mymobkit_video_JpegHandler_initYuv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_shmccam_webcam_video_JpegHandler
 * Method:    encodeYUV420SP
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mymobkit_video_JpegHandler_encodeYUV420SP
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
