/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mymobkit_motion_detection */

#ifndef ANDROID
#define ANDROID android
#endif

#ifndef _Included_com_mymobkit_motion_detection
#define _Included_com_mymobkit_motion_detection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mymobkit_motion_detection
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_com_mymobkit_motion_detection_MotionDetector_nativeCreateObject
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_mymobkit_motion_detection
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mymobkit_motion_detection_MotionDetector_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mymobkit_motion_detection
 * Method:    nativeStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mymobkit_motion_detection_MotionDetector_nativeStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mymobkit_motion_detection
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mymobkit_motion_detection_MotionDetector_nativeStop
  (JNIEnv *, jclass, jlong);

  /*
   * Class:     com_mymobkit_motion_detection
   * Method:    nativeSetFaceSize
   * Signature: (JI)V
   */
  JNIEXPORT void JNICALL Java_com_mymobkit_motion_detection_MotionDetector_nativeSetFaceSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_mymobkit_motion_detection
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_mymobkit_motion_detection_MotionDetector_nativeDetect
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
